# Generated by Django 3.1.4 on 2021-01-04 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumbnail',
            new_name='blog_image',
        ),
    ]
