# Generated by Django 3.1.4 on 2021-01-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_auto_20210104_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='blogApp/images/', verbose_name='Blog Image'),
        ),
    ]
